databases:
  - name: klear-ai-db
    databaseName: klearai
    user: klearai

services:
  - type: web
    name: klear-ai
    runtime: node
    buildCommand: npm install && cp prisma/schema.production.prisma prisma/schema.prisma && npx prisma generate && npx prisma db push && npx prisma db seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: klear-ai-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
